### ISSUE TITLE
Build for Windows

### ISSUE THREAD

**Issue by danielrcollins1** [Kitware/KWStyle#101]
I've tried and failed to build KWStyle for Windows (7, 64-bit).

Are there explicit directions for that anywhere?

Or even better, anyone have a pre-built binary?

**Comment by dzenanz** [comment]
KWStyle uses CMake as meta-build system. Take a look here for a tutorial:
https://preshing.com/20170511/how-to-build-a-cmake-based-project/

**Comment by danielrcollins1** [comment]
> 
> 
> KWStyle uses CMake as meta-build system. Take a look here for a tutorial:
> https://preshing.com/20170511/how-to-build-a-cmake-based-project/

Right, I've downloaded CMake, run it, generated the build files for the MinGW format, and then attempting to make from that fails silently. (I'm not even sure if I have all the dependencies or whatever.)

Note that this seems like a _very_ deep build process, esp. to someone planning on just running (and not developing) KWStyle. Would be really great if a prebuilt binary existed.

**Comment by dzenanz** [comment]
[KWStyle.zip](https://github.com/Kitware/KWStyle/files/6869598/KWStyle.zip)
This is compiled on my computer (Win10 x64) with VS2019, so you will need [VC redist](https://aka.ms/vs/16/release/VC_redist.x64.exe) unless you already have it installed (there is a very good chance that you do).

**Comment by danielrcollins1** [comment]
> 
> 
> [KWStyle.zip](https://github.com/Kitware/KWStyle/files/6869598/KWStyle.zip)
> This is compiled on my computer (Win10 x64) with VS2019, so you will need [VC redist](https://aka.ms/vs/16/release/VC_redist.x64.exe) unless you already have it installed (there is a very good chance that you do).

Excellent, I have it running here now. Thank you so much -- that's a huge help!
