### ISSUE TITLE
KWStyle boost is 1.60 (2015-12-17), an update might fix ITK dashboard warnings

### ISSUE THREAD

**Issue by seanm** [Kitware/KWStyle#74]
My ITK dashboards have warnings from KWSys's boost, ex:

https://open.cdash.org/viewBuildError.php?type=1&buildid=5269390

```
[CTest: warning suppressed] /Users/builder/external/ITK-AppleClang-dbg-x86_64-ASanUBSan/KWStyle/Utilities/boost/smart_ptr/bad_weak_ptr.hpp:43:39: warning: dynamic exception specifications are deprecated [-Wdeprecated-dynamic-exception-spec]
    virtual char const * what() const throw()
                                      ^~~~~~~
```

Perhaps/hopefully a newer boost would fix this.

**Comment by thewtex** [comment]
@seanm  has this been addressed by #75 ?

**Comment by seanm** [comment]
Alas no.

Also: I realize I made a typo above: we're talking KWStyle, not KWSys. :)

Is there a mechanism for the ITK dashboards to ignore warnings from 3rd party code?  I guess this is off topic for a KWStyle ticket, but...

**Comment by thewtex** [comment]
Ok, thanks for the effort, and for checking.

Yes, we can have CDash ignore the warnings by adding a regex here:

  https://github.com/InsightSoftwareConsortium/ITK/blob/8bae9edf6506575b5f30a4660ef766183e46f024/CMake/CTestCustom.cmake.in#L58

**Comment by seanm** [comment]
hmmm, it already has:

```
  ".*KWStyle/Utilities.*"
```

so I guess I've misinterpreted cdash's output, and the 2 warnings in that link aren't the KWStyle ones at all...

**Comment by seanm** [comment]
I'm confused... on the cdash summary page, there's a "1" in the warning column for this build:

https://open.cdash.org/viewBuildError.php?type=1&buildid=5285460

what's the 1 warning?  Everything seems to be "warning suppressed" and from KWStyle...

**Comment by thewtex** [comment]
Nothing jumps out. If you build it locally, is there any warnings from KWStyle itself?

**Comment by seanm** [comment]
I can try once master is building again...

**Comment by thewtex** [comment]
Boost updated to 1.67 in #79 -- closing. Please re-open or create a new issue if the problem still exists.
